```{r setup, include=FALSE}
library(dplyr)
library(stringr)
library(tidyverse)
library(readr)
library(ggplot2)
library(lubridate)
library(ggthemes)
library(rjson)
library(RColorBrewer)
library(rworldmap)
library(mapproj)
library(readxl)
library(GGally)
library(plotly)
```

```{r}

```



```{r}
satisfaction_per_brand <- read.csv("data/satisfaction_per_brand.csv")
customerSatisfactionBenchark <- read.csv2("data/customerSatisfactionBenchmark.csv")
cars_by_fuel_type <- read.csv2("data/cars_by_fuel_type.csv")
new_cars_by_fuel_type <- read.csv2("data/new_cars_by_fuel_type.csv")
sales_bmwgroup <- read.csv2("data/sales_bmwgroup.csv")
comparison_sales_market <- read.csv2("data/comparison_sales_market.csv")
full_segment_sales <- read.csv2("data/full_segment_sales.csv")
```

```{r}
full_segment_sales%>%
  group_by(type)%>%
  summarize(Y2020 = sum(X2020.H1),
         Y2019 = sum(X2019.H1))%>%
  gather(key = "year", value = "sales", -type)%>%
  ggplot()+
  geom_col(aes(reorder(type, sales), sales, fill = year), position = "dodge")+
  scale_fill_manual(values = c("#E7222E","#81C4FF"))+
  theme(axis.title.y = element_blank())+
  coord_flip()
```



```{r}
comparison_sales_market%>%
  gather(key = "group", value = "percentage_group", -year)%>%
  filter(group != "total_market")%>%
  filter(group != "BMW")%>%
  filter(year == "2019")%>%
  mutate(ymax = cumsum(percentage_group),
         ymin = c(0, head(ymax, n=-1)),
         label = paste0(group, "\n value: ", round(percentage_group,2)),
         label_position = (ymax + ymin) / 2)%>%
  ggplot(aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill= group)) +
  geom_rect() +
  geom_label(x = 3.5, aes(y = label_position, label = label), size = 3)+
  scale_fill_manual(values = c("#E7222E","#81C4FF"))+
  coord_polar(theta="y") + # Try to remove that to understand how the chart is built initially
  xlim(c(2, 4)) +# Try to remove that to see how to make a pie chart 
  theme(legend.position = "none", axis.title.x = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank())+
  ggtitle("Market share")+
  theme_void()

  
```
```{r}
SummarySalesPerSegment <- full_segment_sales %>%
  group_by(type) %>%
  summarise(Sales = sum(X2020.H1))

SummarySalesPerSegmentBMW <- full_segment_sales %>%
  filter(str_detect(model,"BMW")) %>%
  group_by(type) %>%
  summarise(Sales_BMW = sum(X2020.H1))

MarketShareSegments <- SummarySalesPerSegmentBMW %>%
  right_join(SummarySalesPerSegment)

MarketShareSegments[is.na(MarketShareSegments)] <- 0

MarketShareSegments <- MarketShareSegments %>%
  mutate(DeductedSales = Sales-Sales_BMW) %>%
  select(-Sales)
```

```{r}
MarketShareSegments %>%
  ggplot()+
  geom_col(aes(reorder(type,-Amount), Amount, fill=Sales_type))+
  scale_fill_manual(values = c("#81C4FF","#E7222E"), labels=c("Total Sales", "Sales BMW"))+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))+
  xlab("Segment")
  
```
```{r}
MarketShareSegments%>%
  mutate(type = fct_reorder(type, -Sales_BMW))%>%
  plot_ly(x=~type, y=~Sales_BMW, type='bar', name = "Sales BMW", marker = list(color = "#E7222E"))%>%
  add_trace(y=~DeductedSales, name ="Rest Of Market Sales", marker = list(color = "#81C4FF"))%>%
  layout(yaxis = list(title = 'Amount'), barmode = 'stack')
```


in orde :)
```{r pressure, echo=FALSE}
satisfaction_per_brand%>%
  filter(Brand == "BMW" | Brand == "Audi" | Brand == "Mercedes")%>%
  filter(type == "After.sale.service"| type == "car.servicing" | type == "Driving.experience")%>%
  ggplot()+
  geom_col(aes(x = "", y = score, fill = Brand), position = "dodge")+
  scale_fill_manual(values = c("#81C4FF","#16588E", "#E7222E"))+
  theme(axis.title.x = element_blank())+
  facet_wrap(~type)
```

```{r}
satisfaction_per_brand%>%
  filter(Brand == "BMW" | Brand == "Audi" | Brand == "Mercedes")%>%
  ggplot(aes(x = type, fill = Brand, y = score)) +
  geom_dotplot(binaxis = "y", stackdir = "center", position = "dodge")
```


```{r}
# Get the world map
worldMap <- getMap()

# Member States of the European Union
europeanUnion <- c("Austria", "Albania", "Belgium","Bosnia and Herz.","Bulgaria","Croatia","Cyprus",
                   "Czech Rep.","Denmark","Estonia","Finland","France","Serbia", "Montenegro", "Belarus", "Ukraine", "Monaco",
                   "Germany","Greece","Hungary","Ireland","Italy", "Kosovo", "Latvia", "Liechtenstein",
                   "Lithuania","Luxembourg","Malta","Netherlands", "Macedonia", "Norway", "Poland", "Moldova",
                   "Portugal","Romania","Slovakia","Slovenia","Spain",
                   "Sweden", "Switzerland", "Turkey","United Kingdom")
# Select only the index of states member of the E.U.
indEU <- which(worldMap$NAME%in%europeanUnion)
```

```{r}
# Extract longitude and latitude border's coordinates of members states of E.U. 
europeCoords <- lapply(indEU, function(i){
  df <- data.frame(worldMap@polygons[[i]]@Polygons[[1]]@coords)
  df$region =as.character(worldMap$NAME[i])
  colnames(df) <- list("long", "lat", "region")
  return(df)
})

europeCoords <- do.call("rbind", europeCoords)
```

```{r}
# Add some data for each member
testvalues_region <- cars_by_fuel_type%>%
  filter(Time == "2018")%>%
  select(region, Electricity)

europeCoords$value <- testvalues_region$Electricity[match(europeCoords$region,testvalues_region$region)]
```

```{r}
# Plot the map
P <- ggplot() + geom_polygon(data = europeCoords, aes(x = long, y = lat, group = region, fill = value),
                             colour = "black", size = 0.1) +
  coord_map(xlim = c(-13, 35),  ylim = c(32, 71))

P <- P + scale_fill_gradient(name = "Number of cars", low = "#E7222E", high = "#81C4FF", na.value = "grey50")


P <- P + theme(#panel.grid.minor = element_line(colour = NA), panel.grid.minor = element_line(colour = NA),
               #panel.background = element_rect(fill = NA, colour = NA),
               axis.text.x = element_blank(),
               axis.text.y = element_blank(), axis.ticks.x = element_blank(),
               axis.ticks.y = element_blank(), axis.title = element_blank(),
               #rect = element_blank(),
               plot.margin = unit(0 * c(-1.5, -1.5, -1.5, -1.5), "lines"))
P
```



```{r}
customerSatisfactionBenchark%>%
  filter(brand == "BMW" | brand == "Volkswagen" | brand == "Mercedes-Benz")%>%
  ggplot()+
  geom_line(aes(year, satisfactionScore, color = brand), size = 1.5)+
  scale_color_manual(values = c("#E7222E","#81C4FF","#16588E"))+
  ylim(50,100)

```

```{r}
annual_sales_bmw %>%
  mutate(Market.Share = as.numeric(as.character(annual_sales_bmw$Market.Share))) -> annual_sales_bmw


write.csv(annual_sales_bmw, "data/annualSalesY90-19.csv", row.names = F)
```

```{r}
market_growth <- full_segment_sales %>%
  filter(year == 2019 | year == 2018) %>%
  group_by(type, year) %>%
  summarise(total_sales = sum(sales)) %>%
  spread(year, total_sales) %>%
  summarise(market_growth = round(((`2019`-`2018`)/`2018`)*100,2))

tot_sales_segment <- full_segment_sales %>%
  filter(year == 2019) %>%
  group_by(type) %>%
  summarise(total_sales = sum(sales))

bmw_sales_segment <- full_segment_sales %>%
  filter(year == 2019) %>%
  filter(str_detect(model, 'BMW')) %>%
  summarise(model, sales, type)

bcg_dataset <- left_join(bmw_sales_segment, tot_sales_segment)
bcg_dataset <- left_join(bcg_dataset, market_growth) %>%
  mutate(market_share = round((sales/total_sales)*100, 2))

mean_market_share <- bcg_dataset %>% summarise(mean(market_share))
mean_market_growth <- bcg_dataset %>% summarise(mean(market_growth))
```

```{r}
bcg_dataset %>%
  ggplot()+
  geom_point(aes(market_share, market_growth, size = sales)) +
  geom_hline(yintercept= 0, linetype="dashed", color = "red") +
  geom_vline(xintercept= mean_market_share[1,1], linetype="dashed", color = "red")
```

```{r}
trends$related_queries%>%
  mutate(keyword = as.factor(keyword))%>%
  filter(related_queries == "top",
         keyword == trends$related_queries$keyword[1])%>%
  mutate(hits = as.numeric(subject),
         value = fct_reorder(value, -hits))%>%
  slice(1:25)%>%
  ggplot(aes(value, hits))+
  geom_col()+
  xlab("")+
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 45, hjust=1))
  
  


```


